### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by pehcastro** [StargazerLabs/mesh-core#1]
Hi @chrissiwaffler 
I've managed to use that version with app routes on next and it's working like a charm, thank you. 

Is it possible to update this repo to the latest meshsdk/core version? There are some new providers (such as Maestro) that would be nice to test out

Thanks in advance

**Comment by chrissiwaffler** [comment]
Hi @pehcastro, I'm glad to hear that my repository here helps you.

Yes, I can update it to the newest version.
Just give me one second :)

**Comment by chrissiwaffler** [comment]
@pehcastro, I've updated this repository with the newest changes coming from Mesh.

Please test this update carefully tho!

The Mesh SDK doesn't have the cleanest code base, so there might arise some unexpected issues, since I haven't tested this update yet.

---

I will close this issue.
If you encounter any issues, feel free to create a new issue!!

Happy coding!
